### ISSUE TITLE
Write outputs to /tmp

### ISSUE THREAD

**Issue by RGBCube** [plutoniumm/x#1]
As the title says, stuff saved to tmp might be a good idea. mktemp --tmpdir works for this

**Comment by plutoniumm** [comment]
Hey this is a nice ideal i'll keep logs of what happened

Is there a clean way to do this in one shot without adding a pipe to every command and/or altering what it does?

**Comment by RGBCube** [comment]
You can just use $(mktemp --tmpdir) as an output for commands, assign it to a var etc, it will create the file and print the path:

![image](https://github.com/plutoniumm/x/assets/78925721/9abc6aa1-e6b3-4c2e-a0de-02c2851beced)

**Comment by plutoniumm** [comment]
Sorry yeah I understood that, but how do use it in let's say .ts?

`bun file.ts > tee tmpfile`?

This is obviously doable but I'll have to add one of these in every language which is pretty annoying tbh, is there a better way? Right now I'm willing to settle for just terminal output if its gonna be cumbersome

**Comment by RGBCube** [comment]
> Sorry yeah I understood that, but how do use it in let's say .ts?
> 
> `bun file.ts > tee tmpfile`?
> 
> This is obviously doable but I'll have to add one of these in every language which is pretty annoying tbh, is there a better way? Right now I'm willing to settle for just terminal output if its gonna be cumbersome

No, I mean only for generated files, like when you run tsc, javac or something else. Printing to stdout is good

**Comment by plutoniumm** [comment]
Ig we're good then, since it already prints everything to stdout. I will keep this idea in mind tho, since I do see the value in some form of logging for back reference
